### PR TITLE
Fix a couple of typos

### PR DESCRIPTION
**Pull request by whereswaldon**
Not a big deal, just saw a couple mistakes browsing the FAQ.

### CODE REVIEW

**Comment by whereswaldon** [comment]
I know that the project doesn't use PRs for code change, but I thought it might make sense for fixing the docs. If not, that's fine.

**Comment by gbbr** [comment]
Unfortunately it will only be accepted through https://upspin-review.googlesource.com/
If you've signed the Google CLA the process is quite straightforward. Take [a look](https://github.com/upspin/upspin/blob/master/CONTRIBUTING.md).

**Comment by adg** [comment]
@whereswaldon as @gbbr says, we can't use Pull Requests (our GitHub repo isn't the source of truth for our project; that's https://upspin.googlesource.com)

**Comment by whereswaldon** [comment]
Okay, resubmitted [here](https://upspin-review.googlesource.com/c/upspin/+/15000)

**Pull request closed without merging**
