### PR TITLE
client: ReadAt, Read fixes

### PR DESCRIPTION
**Pull request by n2vi**

### CODE REVIEW

**Comment by rschio** [comment]
I run my tests using this commit and they are passing now, thank you!

**Comment by n2vi** [comment]
Dave,
As far as I can see you're the primary user of ReadAt elsewhere in Upspin. In particular, upspinfs_test.go:216 might be affected by this change. My machine isn't running upspinfs so it is not easy for me to check.

Rob,
To answer my earlier question to you: I conjecture the difference in Read and ReadAt error specification had to do with reading from pipes of some flavor, not relevant to Upspin. As you're reviewing, I'd especially appreciate any thoughts on the origins of the various tests in client/all_test.go and whether we can better use stdlib to simplify.

**Comment by presotto** [comment]
Well, you can run the test without running upspinfs.  It does  its own
mount etc.  I'll take a look.  To be truthful, I broke my upspin vm a few
months ago and haven't taken the time to fix it.

**Comment by presotto** [comment]
Looks  like I use it in cache.go also.  In upspinfs_test, it shouldn't
bother me either way since  I already piss and moan if the length returned
is unexpected.  In cache,go it doesn't  care  if  you return the EOF at
the  short read or  the next read, as long as one happens.  upsinfs_test
is expecting an exact length returned and will error out only if the EOF is
returned when it isn't a short  read so I think we're OK if I understand
the current code.

**Pull request merged**
